### ISSUE TITLE
help with my plugin 1vs1

### ISSUE THREAD

**Issue by Driesboy** [thedeibo/ServerLoveMCPE#5]
Parse error: syntax error, unexpected '$this' (T_VARIABLE) in /Users/Ronny/Desktop/pocketmine/plugins/pocketmine-1vs1-plugin-master-2/src/Minifixio/onevsone/model/Arena.php on line 150

**Comment by thedeibo** [comment]
Issue Irrelevant to ServerLoveMCPE.
I'll see what I can do though.
