### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by astersx** [thedeibo/ServerLoveMCPE#8]
Players can spam with /love.....

**Comment by thedeibo** [comment]
No my knowledge, no. :)

**Comment by astersx** [comment]
Oh , i mean a player can do,  /love name.  /love name...  and breakup  countless times !!! And it spam!!!!

**Comment by astersx** [comment]
1.  the plugin only broadcast wen you like someone,  is like a fast way to tell someone you love him!!!
2. It makes no sense,  if u didnt love someone,  why you can breakup?(there was no love)!!!
3. Players enjoy the plugin !!! Nice Ideea and keep the good work!!!

**Comment by thedeibo** [comment]
breakuo and nolove are two completely different things.
Nolove basically stops a player from being loved . Say now, if P1 loved p2... then p2 broke up.... then p2 can use /nolove to stop any incoming loves.

**Comment by thedeibo** [comment]
ALso, Im glad people like this plugin. It is constantly growing, with help from the community.
I am looking into a plugin cooldown... but it may be a long long while. It is looking at 10% possibility for ServerLoveMCPE. Reason... we are trying to keep the plugin as close as possible to the original plugin. ratchetgame98's ServerLove ( For Bukkit ). We give ideas to each other.
